on:
  repository_dispatch:
  workflow_dispatch:
        
#  release:
#    types: [published]
    
#  push:
#    branches: 
#      - master
      
  schedule:
    - cron: 0 9 * * *
  
#  watch:
#    types: started

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Code
        uses: LiangJC-JS/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: unifreq/linux-5.4.y              # 上游仓库
          target_repository: LiangJC-JS/linux-5.4.y             # 你要推送的仓库
          upstream_branch: main                                 # 默认是拉取上游仓库的master分支
          target_branch: main                                   # 默认推送到你的仓库master分支
          force: true                                           # 是否强制推送
          tags: false                                           # 确定是否使用-tags
